dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install coveralls

script:
  - coverage run --concurrency=multiprocessing --source=asyncbg setup.py test

after_success:
  - coverage combine
  - coveralls
